<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 C:\Users\babay\source\repos\1.01\static\3d\englevmewi.glb -s
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/C:Users\babaysource\repos\1.01static\3denglevmewi.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[-0.06, 0.23, 0.54]} rotation={[0, 0, 0.17]} scale={0}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.mesh_id58.geometry}
        material={gltf.materials['65']}
        position={[-128.32, -13.52, 7.5]}
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.node_id5.geometry}
      material={gltf.materials['35']}
      position={[-0.02, 0, -0.16]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={1.57}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.node_id8.geometry}
      material={gltf.materials['36']}
      position={[-0.14, 0.18, -0.16]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={1.57}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
