<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 C:\Users\babay\source\repos\1.01\static\3d\englev.glb -s
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/3d/englev.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.mesh_id4.geometry}
        material={gltf.materials['34']}
        position={[49.26, -112.87, 161.31]}
        rotation={[-0.88, -0.28, 1.79]}
        scale={0.61}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.mesh_id5.geometry}
        material={gltf.materials['67']}
        position={[-133.14, 17.68, 272.74]}
        rotation={[0, 0.14, 0.09]}
        scale={0.61}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.mesh_id6.geometry}
        material={gltf.materials['69']}
        position={[-79.13, -4.59, 440.6]}
        rotation={[0, 0, 0.14]}
        scale={0.61}
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.node_id43.geometry}
      material={gltf.materials['62']}
      position={[0.15, 0.03, 0.44]}
      rotation={[-Math.PI / 2, 0.61, 0]}
      scale={0}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
