import { sendToSer } from '$lib/send/sendToSer.js';
import type { PageServerLoad } from './$types';

function shortCode(id: string | number): string {
  const s = String(id).padStart(6, '0');
  return `R-${s.slice(-6)}`;
}

function nameOf(user: any): string {
  if (!user) return 'משתמשת';
  const a = user.attributes || user;
  return a.username || 'משתמשת';
}

function initials(name: string): string {
  const parts = String(name || '').trim().split(/\s+/);
  return ((parts[0]?.[0] || '') + (parts[1]?.[0] || parts[0]?.[1] || '')).slice(0, 2) || 'מש';
}

export const load: PageServerLoad = async ({ params, locals, fetch }) => {
  const uid = (locals as any)?.uid;

  let wish: any = null;
  let proposals: any[] = [];
  let loadOk = false;

  try {
    const res: any = await sendToSer(
      { id: params.id },
      '105queryRatsonWithProposals',
      0,
      0,
      false,
      fetch
    );

    const node = res?.data?.ratson?.data;
    if (node) {
      const a = node.attributes || {};
      const owners = a.users_permissions_users?.data ?? [];
      const ownerName = nameOf(owners[0]);

      wish = {
        id: node.id,
        code: shortCode(node.id),
        name: a.name || '(ללא שם)',
        desc: a.desc || '',
        longDes: a.longDes || a.desc || '',
        status: a.status_ratson || (a.fulfilled ? 'fulfilled' : 'open'),
        fulfilled: !!a.fulfilled,
        fulfillmentScore: typeof a.fulfillment_score === 'number' ? a.fulfillment_score : null,
        lastMatchedAt: a.last_matched_at ?? null,
        startDate: a.startDate ?? null,
        finnishDate: a.finnishDate ?? null,
        totalBounti: typeof a.totalbounti === 'number' ? a.totalbounti : null,
        allowJoin: !!a.allowJoin,
        accessMode: a.access_mode ?? 'private',
        language: a.language ?? null,
        lat: a.lat ?? null,
        lng: a.lng ?? null,
        radius: a.radius ?? null,
        locationHint: a.location_hint ?? null,
        subCategory: a.sub_category ?? null,
        isOnline: !!a.isOnline,
        aiMeta: a.ai_meta ?? null,
        logoUrl:
          a.logo?.data?.attributes?.formats?.medium?.url ||
          a.logo?.data?.attributes?.url ||
          null,
        owners: owners.map((u: any) => ({ id: u.id, name: nameOf(u) })),
        ownerName,
        ownerAvatar: initials(ownerName),
        values: (a.vallues?.data ?? []).map((v: any) => ({ id: v.id, name: v.attributes?.valueName })),
        categories: (a.categories?.data ?? []).map((c: any) => ({ id: c.id, name: c.attributes?.name })),
        missions: (a.missions?.data ?? []).map((m: any) => ({ id: m.id, name: m.attributes?.missionName })),
        mashaabims: (a.mashaabims?.data ?? []).map((m: any) => ({ id: m.id, name: m.attributes?.name })),
        matanots: (a.matanots?.data ?? []).map((m: any) => ({ id: m.id, name: m.attributes?.name })),
        extractedMissions: (a.extracted_missions ?? []).map((e: any) => ({
          id: e.id,
          name: e.name,
          hoursEst: e.hoursEst ?? null,
          importance: e.importance || 'nice',
          notes: e.notes || '',
          linkedMissions: (e.missions?.data ?? []).map((m: any) => ({ id: m.id, name: m.attributes?.missionName }))
        })),
        extractedResources: (a.extracted_resources ?? []).map((e: any) => ({
          id: e.id,
          name: e.name,
          kindOf: e.kindOf ?? null,
          quantityEst: e.quantityEst ?? null,
          importance: e.importance || 'nice',
          notes: e.notes || '',
          linkedMashaabims: (e.mashaabims?.data ?? []).map((m: any) => ({ id: m.id, name: m.attributes?.name }))
        })),
        chatForumId: a.chat_forum?.data?.id ?? null,
        processId: a.process?.data?.id ?? null,
        derivedComplexMatanot: a.derivedComplexMatanot?.data
          ? { id: a.derivedComplexMatanot.data.id, name: a.derivedComplexMatanot.data.attributes?.name }
          : null,
      };

      const propsNodes = res?.data?.ratsonProposals?.data ?? [];
      proposals = propsNodes.map((p: any) => {
        const pa = p.attributes || {};
        const proposerUsers = pa.proposer_users?.data ?? [];
        const project = pa.project?.data;
        const firstProposer = proposerUsers[0];
        const proposerName = firstProposer
          ? nameOf(firstProposer)
          : (project?.attributes?.projectName || 'מציעה');
        return {
          id: p.id,
          kind: pa.kind || 'existing_matanot',
          status: pa.status_proposal || 'suggested',
          matchScore: typeof pa.match_score === 'number' ? pa.match_score : null,
          totalPrice: typeof pa.total_price === 'number' ? pa.total_price : null,
          autoGenerated: !!pa.auto_generated,
          createdAt: pa.createdAt ?? null,
          proposerName,
          proposerAvatar: initials(proposerName),
          proposerUsers: proposerUsers.map((u: any) => ({ id: u.id, name: nameOf(u) })),
          proposerProject: project
            ? { id: project.id, name: project.attributes?.projectName }
            : null,
          matanot: pa.matanot?.data
            ? { id: pa.matanot.data.id, name: pa.matanot.data.attributes?.name }
            : null,
          forumId: pa.forum?.data?.id ?? null,
          negoIds: (pa.negos?.data ?? []).map((n: any) => n.id),
          currencyName: pa.matbea?.data?.attributes?.name ?? null,
          currencySymbol: pa.matbea?.data?.attributes?.simbol ?? '₪',
          coveredMissions: (pa.covered_missions ?? []).map((c: any) => ({
            id: c.id,
            extractedMissionIdx: c.extracted_mission_idx,
            hours: c.hours ?? null,
            price: c.price ?? null,
          })),
          coveredResources: (pa.covered_resources ?? []).map((c: any) => ({
            id: c.id,
            extractedResourceIdx: c.extracted_resource_idx,
            quantity: c.quantity ?? null,
            price: c.price ?? null,
          })),
        };
      });
      loadOk = true;
    }
  } catch (e) {
    console.error('[concierge/:id] 105queryRatsonWithProposals failed', e);
  }

  const isOwner = wish ? wish.owners.some((o: any) => String(o.id) === String(uid)) : false;

  return { wish, proposals, loadOk, uid, isOwner };
};
