import { describe, expect, it, vi } from 'vitest';
import { fireEvent, render, waitFor } from '@testing-library/svelte';
import { tick } from 'svelte';
import { readable } from 'svelte/store';
import he from '$lib/translations/he/concierge.json';

/**
 * QA_CONCIERGE_E2E C-6, from the reader's side: what /concierge/[id] shows is
 * the wish's own facts. The page used to print a made-up date, place, budget,
 * "published yesterday 21:14", "6 active offers" and "four parties" for every
 * wish — and offered tabs that filtered nothing.
 *
 * The real `he` strings are used, so a missing translation key shows up here
 * as a missing text.
 */

// ── stubs for everything the page imports that is not under test ────────────
vi.mock('$app/navigation', () => ({ goto: vi.fn(), invalidateAll: vi.fn() }));
vi.mock('svelte-sonner', () => ({ toast: { success: vi.fn(), error: vi.fn(), message: vi.fn() } }));
vi.mock('$lib/stores/uPic.js', () => ({ uPic: readable('') }));
vi.mock('$lib/translations', () => {
  const dict = he as Record<string, string>;
  const t = readable((key: string, vars: Record<string, unknown> = {}) => {
    const raw = dict[key.replace(/^concierge\./, '')] ?? key;
    return raw.replace(/\{\{(\w+)\}\}/g, (_, k) => String(vars[k] ?? ''));
  });
  return { t, locale: readable('he') };
});
const noop = () => {};
vi.mock('$lib/components/money/Money.svelte', () => ({
  // a Svelte 5 component is just `(anchor, props)` — enough to show the amount
  default: (anchor: Comment, props: { amount: number }) => {
    const el = document.createElement('span');
    el.className = 'money';
    el.textContent = String(props.amount);
    anchor.before(el);
  }
}));
vi.mock('$lib/celim/ui/richText.svelte', () => ({ default: noop }));
vi.mock('$lib/components/prPr/mission.svelte', () => ({ default: noop }));
vi.mock('$lib/components/resource/ResourceCreator.svelte', () => ({ default: noop }));
vi.mock('$lib/components/assistant/WishAssistantLauncher.svelte', () => ({ default: noop }));
vi.mock('$lib/components/concierge/ExternalOfferCard.svelte', () => ({ default: noop }));
vi.mock('$lib/components/concierge/ConciergeBell.svelte', () => ({ default: noop }));
vi.mock('$lib/styles/concierge.css', () => ({}));

const Page = (await import('./+page.svelte')).default;

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();

function wish(over: Record<string, unknown> = {}) {
  return {
    id: '16',
    code: 'R-000016',
    name: 'פינת עבודה ביתית',
    longDes: 'שולחן עץ והרכבת מחשב',
    status: 'open',
    createdAt: hoursAgo(3),
    startDate: null,
    finnishDate: null,
    totalBounti: null,
    isOnline: false,
    locationHint: null,
    radius: null,
    ownerName: 'לקוחה',
    ownerAvatar: 'לק',
    chatForumId: null,
    owners: [{ id: '5', name: 'לקוחה' }],
    extractedMissions: [
      { id: 'm1', name: 'נגרות', hoursEst: 4, importance: 'must', notes: '', linkedMissions: [] },
      { id: 'm2', name: 'הרכבת מחשב', hoursEst: 2, importance: 'must', notes: '', linkedMissions: [] }
    ],
    extractedResources: [],
    ...over
  };
}

const proposal = (id: string, status: string, idx = 0, who = `ספק ${id}`) => ({
  id,
  kind: 'custom_offer',
  status,
  matchScore: 0.8,
  totalPrice: 600,
  autoGenerated: false,
  createdAt: hoursAgo(1),
  proposerName: who,
  proposerAvatar: 'סס',
  proposerUsers: [{ id: `u${id}`, name: who }],
  proposerProject: null,
  matanot: null,
  coveredMissions: [{ id: `c${id}`, extractedMissionIdx: idx, hours: 2, price: 600 }],
  coveredResources: []
});

function mount(data: Record<string, unknown> = {}) {
  return render(Page as any, {
    props: {
      data: {
        wish: wish(),
        proposals: [],
        loadOk: true,
        uid: '5',
        isOwner: true,
        enrichment: undefined,
        forumMessages: [],
        missionTemplates: [],
        external: { enabled: false },
        bell: [],
        ...data
      }
    }
  });
}
const textOf = (data?: Record<string, unknown>) => mount(data).container.textContent ?? '';
/** The proposer cards of the plan — not the chronicle or the summary card, where a name legitimately appears. */
const cards = (view: ReturnType<typeof mount>) =>
  [...view.container.querySelectorAll('.pcard')].map((c) => c.textContent ?? '').join(' | ');

const DEMO = [
  'אתמול 21:14',
  'ה׳, 19 ביוני',
  'חיפה והקריות',
  '850–1,200',
  'עריכת משאלה',
  'R-7f3a91',
  'נעה ב.',
  'נועה גולן',
  'ספא טבע',
  'ארבעת הצדדים',
  'הצעות פעילות · 6',
  'דחויות · 2',
  'ארכיון',
  'שליחת הזמנה'
];

describe('/concierge/[id] — the wish’s own facts, never a demo', () => {
  it('prints none of the demo content', () => {
    const out = textOf({ proposals: [proposal('1', 'accepted'), proposal('2', 'suggested', 1)] });
    for (const demo of DEMO) expect(out).not.toContain(demo);
  });

  it('shows the wish’s own code, author, title and real publish time', () => {
    const out = textOf();
    expect(out).toContain('R-000016');
    expect(out).toContain('מאת לקוחה');
    expect(out).toContain('פינת עבודה ביתית');
    expect(out).toContain('פורסמה לפני 3 שעות');
  });

  it('the status badge follows the wish’s status', () => {
    expect(textOf({ wish: wish({ status: 'open' }) })).toContain('משאלה פתוחה');
    const fulfilled = textOf({ wish: wish({ status: 'fulfilled' }) });
    expect(fulfilled).toContain('המשאלה הוגשמה');
    expect(fulfilled).not.toContain('משאלה פתוחה');
  });

  it('shows when / where / budget only when the wisher gave them', () => {
    const bare = mount();
    expect(bare.container.textContent).not.toContain('מתי');
    expect(bare.container.textContent).not.toContain('איפה');
    expect(bare.container.querySelector('.mi-val')).toBeNull(); // no facts, no facts row
    bare.unmount();

    const full = mount({
      wish: wish({
        startDate: '2026-10-10',
        finnishDate: '2026-10-11',
        locationHint: 'נשר',
        radius: 8,
        totalBounti: 3000
      })
    });
    const out = full.container.textContent ?? '';
    expect(out).toContain('מתי');
    expect(out).toContain('→'); // a range
    expect(out).toContain('נשר · עד 8 ק״מ');
    expect(full.container.querySelector('.mi-val .money')?.textContent).toBe('3000');
  });

  it('an online wish says online, not a made-up place', () => {
    const out = textOf({ wish: wish({ isOnline: true, locationHint: 'נשר' }) });
    expect(out).toContain('אונליין');
    expect(out).not.toContain('נשר');
  });

  it('counts the tabs and the proposers from the real proposals', () => {
    const view = mount({
      proposals: [
        proposal('1', 'accepted', 0, 'דנה'),
        proposal('2', 'suggested', 1, 'רון'),
        proposal('3', 'rejected', 0, 'גיל')
      ]
    });
    const out = view.container.textContent ?? '';
    expect(out).toContain('הצעות פעילות · 2');
    expect(out).toContain('נדחו · 1');
    expect(out).toContain('התכנית · 2 מציעים');
    // owner + the two active proposals
    expect(out).toContain('כשכל 3 הצדדים מאשרים');
    // the declined proposal is not among the cards of the active tab
    expect(cards(view)).toContain('דנה');
    expect(cards(view)).not.toContain('גיל');
  });

  it('the “declined” tab really filters — and shows them as declined, not as open questions', async () => {
    const view = mount({
      proposals: [proposal('1', 'accepted', 0, 'דנה'), proposal('3', 'rejected', 0, 'גיל')]
    });
    const tab = [...view.container.querySelectorAll('button.tab')].find((b) =>
      b.textContent?.includes('נדחו')
    ) as HTMLElement;
    await fireEvent.click(tab);
    await tick();
    const shown = cards(view);
    expect(shown).toContain('גיל');
    expect(shown).toContain('נדחתה');
    expect(shown).not.toContain('דנה'); // the active proposal is on the other tab
    expect(shown).not.toContain('✓ בחירה'); // a closed proposal is not offered for choosing
  });

  it('one proposer, and none, are worded as such', () => {
    expect(textOf({ proposals: [proposal('1', 'accepted')] })).toContain('התכנית · מציע/ה אחד/ת');
    const none = textOf();
    expect(none).toContain('התכנית');
    expect(none).not.toContain('מציעים');
    expect(none).toContain('כשההצעות יאושרו');
  });

  it('an empty breakdown is empty, with a way forward — and 0%, not NaN', () => {
    const out = textOf({ wish: wish({ extractedMissions: [], extractedResources: [] }) });
    expect(out).toContain('עוד אין חלקים בתכנית');
    expect(out).toContain('עוד לא זוהו');
    expect(out).not.toContain('NaN');
    expect(out).toContain('0%');
  });

  it('“send to discussion” goes to the wish chat, and is absent when there is none', () => {
    expect(mount({ wish: wish({ chatForumId: '77' }) }).container.querySelector('a[href="/forum/77"]')).not.toBeNull();
    expect(textOf()).not.toContain('שליחה לדיון');
  });
});


/* ───────────────────────────── C-9: negotiating a proposal's terms ───────────── */

const negotiation = (over: Record<string, unknown> = {}) => ({
  canCounter: true,
  round: 1,
  signedBy: 'provider',
  yourTurn: true,
  amount: 6,
  price: 680,
  counters: [
    { round: 1, by: 'provider', amount: 6, price: 680, note: 'השולחן דורש שעתיים נוספות' }
  ],
  ...over
});
const countered = (over: Record<string, unknown> = {}, who = 'דנה') => ({
  ...proposal('1', 'suggested', 0, who),
  negotiation: negotiation(over)
});

describe('/concierge/[id] — negotiating a provider’s terms (C-9)', () => {
  it('shows what the provider put on the table, with the reason', () => {
    const view = mount({ proposals: [countered()] });
    expect(cards(view)).toContain('השולחן דורש שעתיים נוספות');
    expect(cards(view)).toContain('6');
    expect(cards(view)).toContain('680');
  });

  it('answers a counter with approve or counter back — and keeps the old buttons for a first offer', () => {
    const view = mount({ proposals: [countered()] });
    const text = cards(view);
    expect(text).toContain('✓ אישור הגרסה');
    expect(text).toContain('הצעה נגדית');

    const first = mount({ proposals: [{ ...proposal('2', 'suggested', 1, 'רון'), negotiation: negotiation({ round: 0, counters: [], signedBy: 'provider' }) }] });
    expect(cards(first)).toContain('✓ בחירה');
    expect(cards(first)).toContain('הצעה נגדית');
  });

  it('when she put terms on the table herself it waits for the provider — no approving her own terms', () => {
    const view = mount({
      proposals: [countered({ yourTurn: false, signedBy: 'wisher', counters: [{ round: 1, by: 'wisher', amount: 5, price: 640, note: 'התקציב מאפשר חמש שעות' }] })]
    });
    const text = cards(view);
    expect(text).toContain('ממתין/ה לתשובת הספק/ית');
    expect(text).not.toContain('✓ אישור הגרסה');
    expect(text).not.toContain('✓ בחירה');
    expect(text).toContain('התקציב מאפשר חמש שעות');
  });

  it('a proposal with a product behind it has no counter button — that one is priced by quote', () => {
    const view = mount({ proposals: [countered({ canCounter: false })] });
    expect(cards(view)).not.toContain('הצעה נגדית');
  });

  it('the counter form is prefilled with the terms and will not send nothing or a bare number', async () => {
    const view = mount({ proposals: [countered()] });
    const open = [...view.container.querySelectorAll('.pcard button')].find((b) => b.textContent?.includes('הצעה נגדית')) as HTMLElement;
    await fireEvent.click(open);
    await tick();

    const [hours, price] = [...view.container.querySelectorAll('.neg-form input[type="number"]')] as HTMLInputElement[];
    expect(Number(hours.value)).toBe(6);
    expect(Number(price.value)).toBe(680);
    const send = view.container.querySelector('.neg-form button[type="submit"]') as HTMLButtonElement;
    expect(send.disabled).toBe(true);

    await fireEvent.input(price, { target: { value: '640' } });
    await tick();
    expect(send.disabled).toBe(true); // a number with no reason is a veto in disguise

    await fireEvent.input(view.container.querySelector('.neg-form textarea') as HTMLTextAreaElement, {
      target: { value: 'התקציב מאפשר רק שש מאות וארבעים' }
    });
    await tick();
    expect(send.disabled).toBe(false);
  });

  it('sends the counter through counterRatsonProposal', async () => {
    const fetchMock = vi.fn().mockResolvedValue({ json: async () => ({ success: true }) });
    vi.stubGlobal('fetch', fetchMock);
    const reload = vi.fn();
    Object.defineProperty(window, 'location', { configurable: true, value: { ...window.location, reload } });

    const view = mount({ proposals: [countered()] });
    await fireEvent.click(
      [...view.container.querySelectorAll('.pcard button')].find((b) => b.textContent?.includes('הצעה נגדית')) as HTMLElement
    );
    await tick();
    const [, priceInput] = [...view.container.querySelectorAll('.neg-form input[type="number"]')] as HTMLInputElement[];
    await fireEvent.input(priceInput, { target: { value: '640' } });
    await fireEvent.input(view.container.querySelector('.neg-form textarea') as HTMLTextAreaElement, {
      target: { value: 'התקציב מאפשר רק שש מאות וארבעים' }
    });
    await tick();
    await fireEvent.submit(view.container.querySelector('.neg-form') as HTMLFormElement);

    await waitFor(() => expect(fetchMock).toHaveBeenCalled());
    const [, init] = fetchMock.mock.calls[0];
    expect(JSON.parse(init.body)).toEqual({
      actionKey: 'counterRatsonProposal',
      params: { proposalId: '1', ratsonId: '16', hours: 6, price: 640, note: 'התקציב מאפשר רק שש מאות וארבעים' }
    });
    await waitFor(() => expect(reload).toHaveBeenCalled());
  });
});

/* ───────────── C-9: the pace of the wish — silence is consent ───────────── */

describe('/concierge/[id] — the pace of the wish', () => {
  it('shows the owner the pace — 48 hours unless they chose another — and offers the four a rikma does', () => {
    const view = mount();
    const select = view.container.querySelector('#pace-sel') as HTMLSelectElement;
    expect(select).toBeTruthy();
    expect(select.value).toBe('feh');
    expect([...select.options].map((o) => o.value)).toEqual(['feh', 'sth', 'nsh', 'sevend']);
    expect(view.container.textContent).toContain('שתיקה היא הסכמה');
  });

  it('shows the pace the wish already has', () => {
    const view = mount({ wish: wish({ restime: 'sevend' }) });
    expect((view.container.querySelector('#pace-sel') as HTMLSelectElement).value).toBe('sevend');
  });

  it('is the owner’s to change — nobody else is offered it', () => {
    const view = mount({ isOwner: false });
    expect(view.container.querySelector('#pace-sel')).toBeNull();
  });

  it('changing it goes through setWishRestime', async () => {
    const fetchMock = vi.fn().mockResolvedValue({ json: async () => ({ success: true }) });
    vi.stubGlobal('fetch', fetchMock);
    const reload = vi.fn();
    Object.defineProperty(window, 'location', { configurable: true, value: { ...window.location, reload } });

    const view = mount();
    const select = view.container.querySelector('#pace-sel') as HTMLSelectElement;
    await fireEvent.change(select, { target: { value: 'sth' } });

    await waitFor(() => expect(fetchMock).toHaveBeenCalled());
    expect(JSON.parse(fetchMock.mock.calls[0][1].body)).toEqual({
      actionKey: 'setWishRestime',
      params: { ratsonId: '16', restime: 'sth' }
    });
    await waitFor(() => expect(reload).toHaveBeenCalled());
  });

  it('says on a provider’s card when silence will answer — to whoever’s move it is, and to the one waiting', () => {
    const when = '2026-10-12T14:30:00.000Z';
    const mine = mount({ proposals: [countered({ deadlineAt: when })] });
    expect(cards(mine)).toContain('יש לך עד');
    expect(cards(mine)).toContain('יאושרו אוטומטית');

    const theirs = mount({ proposals: [countered({ deadlineAt: when, yourTurn: false, signedBy: 'wisher' })] });
    expect(cards(theirs)).toContain('הצד השני יכול להשיב עד');
  });

  it('shows no deadline once a proposal is closed', () => {
    const view = mount({ proposals: [countered({ deadlineAt: null, canCounter: false })] });
    expect(cards(view)).not.toContain('יאושרו אוטומטית');
  });
});

/* ───────────── C-10: hide, not reject ───────────── */

describe('/concierge/[id] — a first offer can be hidden, never rejected (C-10)', () => {
  const firstContact = (id = '2') => ({
    ...proposal(id, 'suggested', 1, 'רון'),
    negotiation: negotiation({ round: 0, counters: [], signedBy: 'provider', deadlineAt: null })
  });
  const hideButton = (view: ReturnType<typeof mount>) =>
    [...view.container.querySelectorAll('.pcard button')].find((b) => b.textContent?.trim() === 'הסתר') as HTMLElement | undefined;

  it('offers hide on a proposal nobody has countered — and no flat refusal', () => {
    const view = mount({ proposals: [firstContact()] });
    expect(hideButton(view)).toBeTruthy();
    expect(cards(view)).not.toContain('דחייה');
  });

  it('a proposal with no negotiation view at all (a product, a self-offer) is hidden the same way', () => {
    const view = mount({ proposals: [proposal('2', 'suggested', 1, 'רון')] });
    expect(hideButton(view)).toBeTruthy();
  });

  it('once the two sides are talking there is nothing to hide: approve, or counter', () => {
    const view = mount({ proposals: [countered()] });
    expect(hideButton(view)).toBeUndefined();
    expect(cards(view)).not.toContain('דחייה');
    expect(cards(view)).toContain('הצעה נגדית');
  });

  it('a first-contact proposal carries no deadline — silence binds nobody there', () => {
    const view = mount({ proposals: [firstContact()] });
    expect(cards(view)).not.toContain('יאושרו אוטומטית');
  });

  it('hiding goes through hideRatsonProposal, and decides nothing', async () => {
    const fetchMock = vi.fn().mockResolvedValue({ json: async () => ({ success: true }) });
    vi.stubGlobal('fetch', fetchMock);
    const reload = vi.fn();
    Object.defineProperty(window, 'location', { configurable: true, value: { ...window.location, reload } });

    const view = mount({ proposals: [firstContact('2')] });
    await fireEvent.click(hideButton(view) as HTMLElement);

    await waitFor(() => expect(fetchMock).toHaveBeenCalled());
    expect(JSON.parse(fetchMock.mock.calls[0][1].body)).toEqual({
      actionKey: 'hideRatsonProposal',
      params: { proposalId: '2', ratsonId: '16' }
    });
    await waitFor(() => expect(reload).toHaveBeenCalled());
  });

  it('a closed proposal can be hidden too — it is only clutter by then', () => {
    const view = mount({ proposals: [proposal('3', 'rejected', 0, 'גיל')] });
    // the closed ones are on the declined tab
    const tab = [...view.container.querySelectorAll('button.tab')].find((b) => b.textContent?.includes('נדחו')) as HTMLElement;
    tab.click();
    return tick().then(() => expect(hideButton(view)).toBeTruthy());
  });
});

/* ───────────── C-19: closing the consent with parts that have no provider ───────────── */

describe('/concierge/[id] — closing the consent with gaps (C-19)', () => {
  const closeBtn = (view: ReturnType<typeof mount>) =>
    [...view.container.querySelectorAll('button')].find((b) => b.textContent?.includes('סגירת ההסכמה')) as HTMLButtonElement;
  const btnWith = (view: ReturnType<typeof mount>, text: string) =>
    [...view.container.querySelectorAll('button')].find((b) => b.textContent?.includes(text)) as HTMLButtonElement | undefined;

  function setupFetch() {
    const fetchMock = vi.fn().mockResolvedValue({ json: async () => ({ success: true }) });
    vi.stubGlobal('fetch', fetchMock);
    return fetchMock;
  }

  // one of the wish's two parts has an approved provider, the other none
  const gap = () => mount({ proposals: [proposal('1', 'accepted', 0, 'דנה')] });

  it('asks before closing when a part has no approved provider — and says which, and which was a must', async () => {
    const fetchMock = setupFetch();
    const view = gap();
    await fireEvent.click(closeBtn(view));
    await tick();

    const dialog = view.container.querySelector('.close-gaps') as HTMLElement;
    expect(dialog).toBeTruthy();
    expect(dialog.textContent).toContain('ל-1 חלקים עוד אין ספק מאושר');
    expect(dialog.textContent).toContain('הרכבת מחשב'); // the part with no provider
    expect(dialog.textContent).not.toContain('נגרות'); // the covered one is not listed
    expect(dialog.textContent).toContain('סימנת 1 מהם כ״חובה״');
    expect(fetchMock).not.toHaveBeenCalled(); // nothing was closed by that click
  });

  it('“close anyway” closes it, through materializeWish', async () => {
    const fetchMock = setupFetch();
    const view = gap();
    await fireEvent.click(closeBtn(view));
    await tick();
    await fireEvent.click(btnWith(view, 'סגירה בכל זאת') as HTMLElement);

    await waitFor(() => expect(fetchMock).toHaveBeenCalled());
    expect(JSON.parse(fetchMock.mock.calls[0][1].body)).toMatchObject({
      actionKey: 'materializeWish',
      params: { ratsonId: '16' }
    });
  });

  it('“back to the plan” closes nothing and the question goes away', async () => {
    const fetchMock = setupFetch();
    const view = gap();
    await fireEvent.click(closeBtn(view));
    await tick();
    await fireEvent.click(btnWith(view, 'חזרה לתכנית') as HTMLElement);
    await tick();
    expect(view.container.querySelector('.close-gaps')).toBeNull();
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it('a wish whose every part has a provider closes at once — nothing to warn about', async () => {
    const fetchMock = setupFetch();
    const view = mount({ proposals: [proposal('1', 'accepted', 0, 'דנה'), proposal('2', 'accepted', 1, 'רון')] });
    await fireEvent.click(closeBtn(view));
    await waitFor(() => expect(fetchMock).toHaveBeenCalled());
    expect(view.container.querySelector('.close-gaps')).toBeNull();
    expect(JSON.parse(fetchMock.mock.calls[0][1].body).actionKey).toBe('materializeWish');
  });

  it('a part that is only a "nice to have" is listed but not counted as a must', async () => {
    setupFetch();
    const view = mount({
      wish: wish({
        extractedMissions: [
          { id: 'm1', name: 'נגרות', hoursEst: 4, importance: 'must', notes: '', linkedMissions: [] },
          { id: 'm2', name: 'הרכבת מחשב', hoursEst: 2, importance: 'nice', notes: '', linkedMissions: [] }
        ]
      }),
      proposals: [proposal('1', 'accepted', 0, 'דנה')]
    });
    await fireEvent.click(closeBtn(view));
    await tick();
    const dialog = view.container.querySelector('.close-gaps') as HTMLElement;
    expect(dialog.textContent).toContain('הרכבת מחשב');
    expect(dialog.textContent).not.toContain('כ״חובה״');
  });
});

describe('/concierge/[id] — the deal’s stages (PLAN_DIRECT_OFFER P1)', () => {
  it('heads the page with the real stages, not a dial stuck on "proposals"', async () => {
    const { dealStages } = await import('$lib/sheirut/dealChain');
    const stages = dealStages(
      { wishId: '16', requests: [{ id: '5', dealId: '8' }], deals: [{ id: '8', closed: false }] },
      { kind: 'wish', id: '16' }
    );
    const view = mount({ stages });
    const nav = view.container.querySelector('nav.ds-concierge');
    expect(nav).not.toBeNull();
    const hrefs = [...nav!.querySelectorAll('a')].map((a) => a.getAttribute('href'));
    expect(hrefs).toEqual(['/deals/request/5', '/deals/8']);
    expect(nav!.querySelector('[aria-current="step"]')).not.toBeNull();
    for (const old of ['UNDERSTAND', 'PROPOSALS', 'CONSENT']) expect(view.container.textContent).not.toContain(old);
  });

  it('a page loaded without stages shows no strip', () => {
    expect(mount().container.querySelector('nav.ds')).toBeNull();
  });
});

describe('/concierge/[id] — new details are a new version (PLAN_DIRECT_OFFER §4.3)', () => {
  const heText = (k: string) => (he as Record<string, string>)[k];
  const negotiation = (over: Record<string, unknown> = {}) => ({
    canCounter: true,
    round: 0,
    signedBy: 'wisher',
    yourTurn: false,
    amount: 2,
    price: 600,
    deadlineAt: null,
    counters: [],
    termsChanged: true,
    ...over
  });

  it('the owner can change the details of an open wish, and not of a fulfilled one', () => {
    expect(mount().container.querySelector('.wt-open')).not.toBeNull();
    expect(mount({ wish: wish({ status: 'fulfilled' }) }).container.querySelector('.wt-open')).toBeNull();
    expect(mount({ isOwner: false }).container.querySelector('.wt-open')).toBeNull();
  });

  it('after she changed them, a signed proposal waits for the provider — not for her approval', () => {
    const view = mount({ proposals: [{ ...proposal('1', 'suggested'), proposalId: '1', negotiation: negotiation() }] });
    expect(view.container.textContent).toContain(heText('neg_waiting_terms'));
    expect(view.container.textContent).not.toContain('✓ בחירה');
  });
});
