import { describe, expect, it, vi } from 'vitest';
import { fireEvent, render } from '@testing-library/svelte';
import { tick } from 'svelte';
import { readable } from 'svelte/store';
import he from '$lib/translations/he/concierge.json';

/**
 * QA_CONCIERGE_E2E C-6, from the reader's side: what /concierge/[id] shows is
 * the wish's own facts. The page used to print a made-up date, place, budget,
 * "published yesterday 21:14", "6 active offers" and "four parties" for every
 * wish — and offered tabs that filtered nothing.
 *
 * The real `he` strings are used, so a missing translation key shows up here
 * as a missing text.
 */

// ── stubs for everything the page imports that is not under test ────────────
vi.mock('$app/navigation', () => ({ goto: vi.fn(), invalidateAll: vi.fn() }));
vi.mock('svelte-sonner', () => ({ toast: { success: vi.fn(), error: vi.fn(), message: vi.fn() } }));
vi.mock('$lib/stores/uPic.js', () => ({ uPic: readable('') }));
vi.mock('$lib/translations', () => {
  const dict = he as Record<string, string>;
  const t = readable((key: string, vars: Record<string, unknown> = {}) => {
    const raw = dict[key.replace(/^concierge\./, '')] ?? key;
    return raw.replace(/\{\{(\w+)\}\}/g, (_, k) => String(vars[k] ?? ''));
  });
  return { t, locale: readable('he') };
});
const noop = () => {};
vi.mock('$lib/components/money/Money.svelte', () => ({
  // a Svelte 5 component is just `(anchor, props)` — enough to show the amount
  default: (anchor: Comment, props: { amount: number }) => {
    const el = document.createElement('span');
    el.className = 'money';
    el.textContent = String(props.amount);
    anchor.before(el);
  }
}));
vi.mock('$lib/celim/ui/richText.svelte', () => ({ default: noop }));
vi.mock('$lib/components/prPr/mission.svelte', () => ({ default: noop }));
vi.mock('$lib/components/resource/ResourceCreator.svelte', () => ({ default: noop }));
vi.mock('$lib/components/assistant/WishAssistantLauncher.svelte', () => ({ default: noop }));
vi.mock('$lib/components/concierge/ExternalOfferCard.svelte', () => ({ default: noop }));
vi.mock('$lib/components/concierge/ConciergeBell.svelte', () => ({ default: noop }));
vi.mock('$lib/styles/concierge.css', () => ({}));

const Page = (await import('./+page.svelte')).default;

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();

function wish(over: Record<string, unknown> = {}) {
  return {
    id: '16',
    code: 'R-000016',
    name: 'פינת עבודה ביתית',
    longDes: 'שולחן עץ והרכבת מחשב',
    status: 'open',
    createdAt: hoursAgo(3),
    startDate: null,
    finnishDate: null,
    totalBounti: null,
    isOnline: false,
    locationHint: null,
    radius: null,
    ownerName: 'לקוחה',
    ownerAvatar: 'לק',
    chatForumId: null,
    owners: [{ id: '5', name: 'לקוחה' }],
    extractedMissions: [
      { id: 'm1', name: 'נגרות', hoursEst: 4, importance: 'must', notes: '', linkedMissions: [] },
      { id: 'm2', name: 'הרכבת מחשב', hoursEst: 2, importance: 'must', notes: '', linkedMissions: [] }
    ],
    extractedResources: [],
    ...over
  };
}

const proposal = (id: string, status: string, idx = 0, who = `ספק ${id}`) => ({
  id,
  kind: 'custom_offer',
  status,
  matchScore: 0.8,
  totalPrice: 600,
  autoGenerated: false,
  createdAt: hoursAgo(1),
  proposerName: who,
  proposerAvatar: 'סס',
  proposerUsers: [{ id: `u${id}`, name: who }],
  proposerProject: null,
  matanot: null,
  coveredMissions: [{ id: `c${id}`, extractedMissionIdx: idx, hours: 2, price: 600 }],
  coveredResources: []
});

function mount(data: Record<string, unknown> = {}) {
  return render(Page as any, {
    props: {
      data: {
        wish: wish(),
        proposals: [],
        loadOk: true,
        uid: '5',
        isOwner: true,
        enrichment: undefined,
        forumMessages: [],
        missionTemplates: [],
        external: { enabled: false },
        bell: [],
        ...data
      }
    }
  });
}
const textOf = (data?: Record<string, unknown>) => mount(data).container.textContent ?? '';
/** The proposer cards of the plan — not the chronicle or the summary card, where a name legitimately appears. */
const cards = (view: ReturnType<typeof mount>) =>
  [...view.container.querySelectorAll('.pcard')].map((c) => c.textContent ?? '').join(' | ');

const DEMO = [
  'אתמול 21:14',
  'ה׳, 19 ביוני',
  'חיפה והקריות',
  '850–1,200',
  'עריכת משאלה',
  'R-7f3a91',
  'נעה ב.',
  'נועה גולן',
  'ספא טבע',
  'ארבעת הצדדים',
  'הצעות פעילות · 6',
  'דחויות · 2',
  'ארכיון',
  'שליחת הזמנה'
];

describe('/concierge/[id] — the wish’s own facts, never a demo', () => {
  it('prints none of the demo content', () => {
    const out = textOf({ proposals: [proposal('1', 'accepted'), proposal('2', 'suggested', 1)] });
    for (const demo of DEMO) expect(out).not.toContain(demo);
  });

  it('shows the wish’s own code, author, title and real publish time', () => {
    const out = textOf();
    expect(out).toContain('R-000016');
    expect(out).toContain('מאת לקוחה');
    expect(out).toContain('פינת עבודה ביתית');
    expect(out).toContain('פורסמה לפני 3 שעות');
  });

  it('the status badge follows the wish’s status', () => {
    expect(textOf({ wish: wish({ status: 'open' }) })).toContain('משאלה פתוחה');
    const fulfilled = textOf({ wish: wish({ status: 'fulfilled' }) });
    expect(fulfilled).toContain('המשאלה הוגשמה');
    expect(fulfilled).not.toContain('משאלה פתוחה');
  });

  it('shows when / where / budget only when the wisher gave them', () => {
    const bare = mount();
    expect(bare.container.textContent).not.toContain('מתי');
    expect(bare.container.textContent).not.toContain('איפה');
    expect(bare.container.querySelector('.mi-val')).toBeNull(); // no facts, no facts row
    bare.unmount();

    const full = mount({
      wish: wish({
        startDate: '2026-10-10',
        finnishDate: '2026-10-11',
        locationHint: 'נשר',
        radius: 8,
        totalBounti: 3000
      })
    });
    const out = full.container.textContent ?? '';
    expect(out).toContain('מתי');
    expect(out).toContain('→'); // a range
    expect(out).toContain('נשר · עד 8 ק״מ');
    expect(full.container.querySelector('.mi-val .money')?.textContent).toBe('3000');
  });

  it('an online wish says online, not a made-up place', () => {
    const out = textOf({ wish: wish({ isOnline: true, locationHint: 'נשר' }) });
    expect(out).toContain('אונליין');
    expect(out).not.toContain('נשר');
  });

  it('counts the tabs and the proposers from the real proposals', () => {
    const view = mount({
      proposals: [
        proposal('1', 'accepted', 0, 'דנה'),
        proposal('2', 'suggested', 1, 'רון'),
        proposal('3', 'rejected', 0, 'גיל')
      ]
    });
    const out = view.container.textContent ?? '';
    expect(out).toContain('הצעות פעילות · 2');
    expect(out).toContain('נדחו · 1');
    expect(out).toContain('התכנית · 2 מציעים');
    // owner + the two active proposals
    expect(out).toContain('כשכל 3 הצדדים מאשרים');
    // the declined proposal is not among the cards of the active tab
    expect(cards(view)).toContain('דנה');
    expect(cards(view)).not.toContain('גיל');
  });

  it('the “declined” tab really filters — and shows them as declined, not as open questions', async () => {
    const view = mount({
      proposals: [proposal('1', 'accepted', 0, 'דנה'), proposal('3', 'rejected', 0, 'גיל')]
    });
    const tab = [...view.container.querySelectorAll('button.tab')].find((b) =>
      b.textContent?.includes('נדחו')
    ) as HTMLElement;
    await fireEvent.click(tab);
    await tick();
    const shown = cards(view);
    expect(shown).toContain('גיל');
    expect(shown).toContain('נדחתה');
    expect(shown).not.toContain('דנה'); // the active proposal is on the other tab
    expect(shown).not.toContain('✓ בחירה'); // a closed proposal is not offered for choosing
  });

  it('one proposer, and none, are worded as such', () => {
    expect(textOf({ proposals: [proposal('1', 'accepted')] })).toContain('התכנית · מציע/ה אחד/ת');
    const none = textOf();
    expect(none).toContain('התכנית');
    expect(none).not.toContain('מציעים');
    expect(none).toContain('כשההצעות יאושרו');
  });

  it('an empty breakdown is empty, with a way forward — and 0%, not NaN', () => {
    const out = textOf({ wish: wish({ extractedMissions: [], extractedResources: [] }) });
    expect(out).toContain('עוד אין חלקים בתכנית');
    expect(out).toContain('עוד לא זוהו');
    expect(out).not.toContain('NaN');
    expect(out).toContain('0%');
  });

  it('“send to discussion” goes to the wish chat, and is absent when there is none', () => {
    expect(mount({ wish: wish({ chatForumId: '77' }) }).container.querySelector('a[href="/forum/77"]')).not.toBeNull();
    expect(textOf()).not.toContain('שליחה לדיון');
  });
});
