/**
 * Visual placeholder for assets that will be swapped in by the video editor:
 *   - 'screenshot' → real app screenshot from the site
 *   - 'ai-video'   → clip from a generative video tool (Sora / Runway / Kling)
 *   - 'ai-image'   → single frame generated by Midjourney / Ideogram / FLUX
 *
 * In production: replace <Placeholder> with <Img src={staticFile('...')} />
 * or a <Video src={staticFile('...')} startFrom={0} />.
 */
import React from 'react';
import {AbsoluteFill, interpolate, spring, useCurrentFrame, useVideoConfig} from 'remotion';
import {theme} from './theme';

export type PlaceholderKind = 'screenshot' | 'ai-video' | 'ai-image';

export interface PlaceholderProps {
  kind: PlaceholderKind;
  label: string;
  prompt: string;
  width?: number;
  height?: number;
  style?: React.CSSProperties;
}

const KIND_COLOR: Record<PlaceholderKind, string> = {
  screenshot: '#5be2a9',
  'ai-video':  '#bf953f',
  'ai-image':  '#a855f7',
};

const KIND_ICON: Record<PlaceholderKind, string> = {
  screenshot:  '📱',
  'ai-video':  '🎬',
  'ai-image':  '🎨',
};

const KIND_LABEL: Record<PlaceholderKind, string> = {
  screenshot: 'צילום מסך',
  'ai-video': 'קליפ AI',
  'ai-image': 'תמונת AI',
};

export const Placeholder: React.FC<PlaceholderProps> = ({
  kind,
  label,
  prompt,
  width = 680,
  height = 380,
  style,
}) => {
  const frame = useCurrentFrame();
  const {fps} = useVideoConfig();
  const in1 = spring({frame, fps, config: {damping: 20}});
  const col = KIND_COLOR[kind];
  const dash = (frame / 2) % 24;

  return (
    <div
      style={{
        width,
        height,
        borderRadius: 24,
        background: 'rgba(255,255,255,0.04)',
        border: `2px dashed ${col}`,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 14,
        opacity: interpolate(in1, [0, 1], [0, 1]),
        transform: `scale(${interpolate(in1, [0, 1], [0.96, 1])})`,
        padding: '28px 36px',
        textAlign: 'center',
        direction: 'rtl',
        ...style,
      }}
    >
      <div style={{fontSize: 56}}>{KIND_ICON[kind]}</div>

      <div
        style={{
          background: col,
          color: '#0f1520',
          fontFamily: theme.font,
          fontWeight: 800,
          fontSize: 20,
          padding: '5px 18px',
          borderRadius: 999,
          letterSpacing: 1,
        }}
      >
        {KIND_LABEL[kind]}
      </div>

      <div style={{fontFamily: theme.font, fontWeight: 700, fontSize: 30, color: theme.colors.white}}>
        {label}
      </div>

      <div
        style={{
          fontFamily: theme.font,
          fontWeight: 400,
          fontSize: 20,
          color: 'rgba(255,255,255,0.5)',
          lineHeight: 1.45,
          maxWidth: width - 80,
        }}
      >
        <span style={{color: col, fontWeight: 600}}>פרומפט:</span> {prompt}
      </div>
    </div>
  );
};
