<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 static/3d/11.glb
-->

<script>
  import {spring } from 'svelte/motion'
  import { Group, SpotLight } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
 // import { onMount } from 'svelte';
  export let s = 0
 /* onMount(()=>{
    top.set(4)
    setTimeout(top.set(0),3000)
  })*/
  export const ref = new Group()

  const gltf = useGltf('3d/11.glb')

  const component = forwardEventHandlers()
   const top = spring(0)
   export let fi = false, hover = false, scrolli = false
  $: if(fi == true){
    top.set(7,{duration:3000})
  }else if(hover == true){
      console.log("true")
    top.set(1.5,{duration:3000})
  }else if(scrolli == true){
    top.set(0.5,{duration:3000})
  }else{
    top.set(0,{duration:3000})
  }
   let rotationt = 0
  export let poz = {z:0, y:0, x:0};

    let arr = new Array(100)
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
  <T.AmbientLight  />
  <T.AmbientLight    intensity={1} rotation={345}/>

<T.AmbientLight  intensity={1} />


<T.SpotLight position={{ y: -20, z: -5, x: 5 }} />

<T.DirectionalLight   intensity={0.81} position={{ y: -20, z: -5, x: 5 }} />
<T.DirectionalLight  intensity={0.91} position={{ y: 10, z: 10 }} />
<T.DirectionalLight  intensity={0.91} position={[ 0,-2,0 ]} />

    <T.Group position={[(-poz.y/10)-2.4, $top+(-1.5), 0.45]} scale={0.008}>
      <T.Mesh 
        geometry={gltf.nodes.node_id38.geometry}
        material={gltf.materials['312']}
        rotation={[-Math.PI, 0.52, -Math.PI]}
        scale={43.6}
      />
    </T.Group>
    <T.Group position={[(poz.y/10)+2.4, $top+(-1.5), 0.45]} scale={0.008}>
      <T.Mesh
        geometry={gltf.nodes.node_id66.geometry}
        material={gltf.materials['312']}
        rotation={[Math.PI, -0.52, Math.PI]}
        scale={[-43.6, 43.6, 43.6]}
      />
    </T.Group>
    <T.Group  position={[-0.02, $top+1.3, 0.3-$top]} rotation={[1.33, 0, (poz.y/2)]} scale={0.005}>
      <T.Mesh
        geometry={gltf.nodes.node_id146.geometry}
        material={gltf.materials['283']}
        position={[-5.17, $top+0, 471.72]}
        rotation={[Math.PI, 0, 0]}
        scale={1.02}
      />
      <T.Mesh
        geometry={gltf.nodes.node_id148.geometry}
        material={gltf.materials['285']}
        position={[-5.17, $top+0, 471.72]}
        rotation={[Math.PI, 0, 0]}
        scale={1.02}
      />
    <T.Mesh
      geometry={gltf.nodes.node_id6.geometry}
      material={gltf.materials['306']}
      position={[-1, -1-($top), (poz.y/20)]}
      rotation={[-2, (Math.PI / 4),(poz.y/20) ]}
      scale={0.04}
    />
   
    </T.Group>
    <!--לב זהב 
    <T.Mesh
      geometry={gltf.nodes.node_id6.geometry}
      material={gltf.materials['306']}
      position={[-1.2+s, -1, 0]}
      rotation={[-2, (Math.PI / 4),(poz.y/20) ]}
      scale={0.004*poz.y > 0 ? (0.004*poz.y)/2 : -((0.004*poz.y)/20)}
    />-->
    <!--קערה תחתונה-->
    <T.Mesh 
      rotation={[(poz.y/20)-2.1,(poz.y/20),0]}
      geometry={gltf.nodes.node_id75.geometry}
      material={gltf.materials['308']}
      position={[-0.01, $top+(-3), 0.01]}
      scale={1.29}
    />
    <!--כתר-->
    <T.Mesh
    c
      rotation={[0+$top/3 ,(poz.y/2),0]}  
      geometry={gltf.nodes.node_id102.geometry}
      material={gltf.materials['310']}
      position={[-0.01, 2.4-$top/8, 0.31]}
      scale={0.01+$top/433}
    />
      <T.SpotLight position={[-0.01, $top+2.4, 0.31]} />
      <T.SpotLight position={[-0.01, 2.4-$top/8, 0.31]}/>
      {#each arr as ar , i}
      <T.Mesh
      geometry={gltf.nodes.node_id6.geometry}
      material={gltf.materials['306']}
      position={[Math.ceil(Math.random() * 13) * (Math.round(Math.random()) ? 1 : -1), $top+(-2),Math.ceil(Math.random() * 13) * (Math.round(Math.random()) ? 1 : -1)]}
      rotation={[poz.y,poz.y,poz.y]}
      scale={0.0002*poz.y}
    />
    {/each}
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
