<!-- @migration-task Error while migrating Svelte code: Cannot use `$$restProps` in runes mode -->
<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 static/3d/11.glb
-->

<script>
  import { spring } from 'svelte/motion'
  import { CylinderGeometry, Group, SpotLight, TextureLoader, MirroredRepeatWrapping } from 'three'
  import { T, forwardEventHandlers, useLoader } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  const texture = useLoader(TextureLoader).load('https://res.cloudinary.com/love1/image/upload/v1640020897/cropped-PicsArt_01-28-07.49.25-1_wvt4qz.png')
  const geometry = new CylinderGeometry(5, 5, 0.5, 32)

  // Props using runes
  let { 
    ref = new Group(), 
    fi = false, 
    hover = false, 
    scrolli = false,
    children = {
      fallback: null,
      error: null,
      default: null
    }
  } = $props()
  let { poz = { z: 0, y: 0, x: 0 } } = $props()

  const gltf = useGltf('3d/11.glb')
  const component = forwardEventHandlers()
  
  // State management with runes
  const top = spring(0)
  let rotationt = 0
  
  let arr = new Array(100)
  let arr2 = new Array(50)

  // Effect using runes
  $effect(() => {
    if (fi) {
      top.set(7, { duration: 3000 })
    } else if (hover) {
      console.log("true")
      top.set(1.5, { duration: 3000 })
    } else if (scrolli) {
      top.set(0.5, { duration: 3000 })
    } else {
      top.set(0, { duration: 3000 })
    }
  })
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    {#if children.fallback}
      {children.fallback}
    {/if}
  {:then gltf}
  
 


<T.SpotLight position={{ y: -20, z: -5, x: 5 }} />

<T.DirectionalLight   intensity={0.81} position={{ y: -20, z: -5, x: 5 }} />
<T.DirectionalLight  intensity={0.91} position={[(poz.y/10)+2.4, $top+(-1.5), 0.45]} />
<T.DirectionalLight  intensity={0.91} position={[ 0,-2,0 ]} />
<T.DirectionalLight  intensity={1} position={[(-poz.y/10)-2.4, $top+(-1.5), 0.45]} />
<T.DirectionalLight  intensity={0.91} position={[-5.17, $top+0, 471.72]} />
<T.DirectionalLight  intensity={0.91} position={[-1, -1-($top), (poz.y/20)]} />

    <T.Group position={[(-poz.y/10)-2.4, $top+(-1.5), 0.45]} scale={0.008}>
      <T.Mesh 
        geometry={gltf.nodes.node_id38.geometry}
        material={gltf.materials['312']}
        rotation={[-Math.PI, 0.52, -Math.PI]}
        scale={43.6}
      />
    </T.Group>
    <T.Group position={[(poz.y/10)+2.4, $top+(-1.5), 0.45]} scale={0.008}>
      <T.Mesh
        geometry={gltf.nodes.node_id66.geometry}
        material={gltf.materials['312']}
        rotation={[Math.PI, -0.52, Math.PI]}
        scale={[-43.6, 43.6, 43.6]}
      />
    </T.Group>
    <T.Group  position={[-0.02, $top+1.3, 0.3-$top]} rotation={[1.33, 0, (poz.y/2)]} scale={0.005}>
      <T.Mesh
        geometry={gltf.nodes.node_id146.geometry}
        material={gltf.materials['283']}
        position={[-5.17, $top+0, 471.72]}
        rotation={[Math.PI, 0, 0]}
        scale={1.02}
      />
      <T.Mesh
        geometry={gltf.nodes.node_id148.geometry}
        material={gltf.materials['285']}
        position={[-5.17, $top+0, 471.72]}
        rotation={[Math.PI, 0, 0]}
        scale={1.02}
      />
    <T.Mesh
      geometry={gltf.nodes.node_id6.geometry}
      material={gltf.materials['306']}
      position={[-1, -1-($top), (poz.y/20)]}
      rotation={[-2, (Math.PI / 4),(poz.y/20) ]}
      scale={0.04}
    />
   
    </T.Group>
    <!--לב זהב 
    <T.Mesh
      geometry={gltf.nodes.node_id6.geometry}
      material={gltf.materials['306']}
      position={[-1.2+s, -1, 0]}
      rotation={[-2, (Math.PI / 4),(poz.y/20) ]}
      scale={0.004*poz.y > 0 ? (0.004*poz.y)/2 : -((0.004*poz.y)/20)}
         geometry={gltf.nodes.node_id75.geometry}
 />-->
    
    {#if $texture}
          {#each arr2 as ar , i}

  <T.Mesh 
    {geometry}
      rotation={[(poz.y),(poz.y),poz.y+$top]}
      position={[Math.ceil(Math.random() * 1) * (Math.round(Math.random()) ? 1 : -1), $top-1,Math.ceil(Math.random() * 5) * (Math.round(Math.random()) ? 1 : -1),-2]}
      scale={0.07}> 
   <T.MeshStandardMaterial color="#EEE8AA" map={$texture}  />
  </T.Mesh>
{/each}
  {/if}

    <!--כתר-->
    <T.Mesh
    c
      rotation={[0+$top/3 ,(poz.y/2),0]}  
      geometry={gltf.nodes.node_id102.geometry}
      material={gltf.materials['310']}
      position={[-0.01, fi == true?2.4+$top/2 :2.4-$top/8, 0.31]}
      scale={0.01+$top/433}
    />
      <T.SpotLight position={[-0.01, $top+2.4, 0.31]} />
      <T.SpotLight position={[-0.01, 2.4-$top/8, 0.31]}/>
      {#each arr as ar , i}
      <T.Mesh
      geometry={gltf.nodes.node_id6.geometry}
      material={gltf.materials['306']}
      position={[Math.ceil(Math.random() * 13) * (Math.round(Math.random()) ? 1 : -1), $top+(-2),Math.ceil(Math.random() * 13) * (Math.round(Math.random()) ? 1 : -1)]}
      rotation={[poz.y,poz.y,poz.y]}
      scale={0.0002*poz.y}
    />
    {/each}
   
    <!--- <Coiner/>
    <GLTF
      url="3d/coiner.glb"  
      rotation={[(poz.y/2)-2,(poz.y/20),0]}
      position={[-0.01,fi == true? $top*2+(-6) : $top+(-6), 0.01]}
      scale={10.29}
      />
      <T.AmbientLight/>
      <T.DirectionalLight   intensity={0.81} position={[-0.01,fi == true? $top*2+(-6) : $top+(-6), 0.01]} />

            <T.SpotLight position={[-0.01,fi == true? $top*2+(-6) : $top+(-6), 0.01]}/>
-->
  {:catch error}
    {#if children.error}
      {@const errorProps = { error }}
      {children.error(errorProps)}
    {/if}
  {/await}

  {#if children.default}
    {children.default({ ref })}
  {/if}
</T>
