<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 static/3d/coiner.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('3d/coiner.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
<T.AmbientLight/>
    <T.Mesh
      geometry={gltf.nodes.mesh_id27.geometry}
      material={gltf.materials['68']}
      position={[-0.01, -2.02, 0.2]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.01}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
