<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 static/3d/withlev.glb
-->

<script>
    import {spring } from 'svelte/motion'
  import { Group } from 'three'
  import { useFrame, T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
   import { interactivity } from '@threlte/extras'
  interactivity()
  import { createEventDispatcher } from 'svelte';
 const dispatch = createEventDispatcher();
  export const ref = new Group()

  const gltf = useGltf('3d/withlev.glb')

   let rotationt = 0
		let isHovering = false, isPointerDown = false
  let poz = {z:0, y:0, x:0};
  let obPoz = {z:0, y:0, x:0}
 let boll = false
 let bool = false
 const texter = spring(1)
 useFrame(() => {

  if(isHovering == false){
	rotationt += 0.01
      texter.set(1)

  } else{
    rotationt = 0
    texter.set(1.3)
  }
})
function sub (){
    console.log("click")
    dispatch("submit")
}
</script>
<T.PerspectiveCamera makeDefaulte position={[ 0, 0 ,25]} fov={24}/>
<T.AmbientLight   intensity={0.61} />

<T.SpotLight position={poz} />

<T.DirectionalLight  intensity={0.81} position={[ -20,  -5, 5 ]} />
<T.DirectionalLight  intensity={0.91} position={[0, 10, 10 ]} />
<T is={ref} dispose={false} {...$$restProps} on:pointerenter={() => (isHovering = true)}
on:pointerleave={() => {
  isPointerDown = false
  isHovering = false
}}
on:pointerdown={() => (isPointerDown = true)}
on:pointerup={() => (isPointerDown = false)}
on:pointercancel={() => {
  isPointerDown = false
  isHovering = false
}}
on:click={sub} >
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
        <T.Group  rotation={[0, rotationt, 0.1]} >
<T.AmbientLight   intensity={0.61} />

<T.SpotLight position={poz} />

<T.DirectionalLight  intensity={0.81} position={[-0.4, 0.1, 3.2]} />
<T.DirectionalLight  intensity={0.91} position={{ y: 10, z: 10 }} />
    <T.Group position={[-0.4, 0.1, 3.2]} scale={0.005} rotation={[0, 0, 0]}>
      <T.Group scale={$texter} >
        <T.Mesh
        castShadow receiveShadow
          geometry={gltf.nodes.mesh_id99.geometry}
          material={gltf.materials['90']}         
        />
      <T.Mesh
      castShadow receiveShadow
        geometry={gltf.nodes.node_id118.geometry}
        material={gltf.materials['85']}
        scale={6}
        rotation={[0, 0, 0]}
        position={[-4.4, 7, 8.2]}
      />
      </T.Group>
    </T.Group>
    <T.Mesh
    castShadow receiveShadow
      geometry={gltf.nodes.node_id74.geometry}
      material={gltf.materials['70']}
      position={[-0.2, -2.19, 0.21]}
      rotation={[0.34, 0, -0.16]}
      scale={0.22}
    />
  </T.Group  >

  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
