<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 static/3d/placid_gears/scene.gltf
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/placid-gears-88e519e409634a7990c1b37eb86f6f3c
Title: Placid Gears
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('3d/placid_gears/scene.gltf')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="root">
          <T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
            <T.Group name="Gear_0">
              <T.Mesh
                name="Object_4"
                geometry={gltf.nodes.Object_4.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear003_1" position={[0, 0, -1.5]}>
              <T.Mesh
                name="Object_6"
                geometry={gltf.nodes.Object_6.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear004_2" position={[1.5, 0, -3.5]}>
              <T.Mesh
                name="Object_8"
                geometry={gltf.nodes.Object_8.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear001_3" position={[1.97, 0, -0.51]}>
              <T.Mesh
                name="Object_10"
                geometry={gltf.nodes.Object_10.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear002_4" position={[6.07, 0, -2.45]}>
              <T.Mesh
                name="Object_12"
                geometry={gltf.nodes.Object_12.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear005_5" position={[6.07, 0, -0.95]}>
              <T.Mesh
                name="Object_14"
                geometry={gltf.nodes.Object_14.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear006_6" position={[4.57, 0, 1.05]}>
              <T.Mesh
                name="Object_16"
                geometry={gltf.nodes.Object_16.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear007_7" position={[4.1, 0, -1.95]}>
              <T.Mesh
                name="Object_18"
                geometry={gltf.nodes.Object_18.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear008_8" position={[-2.5, 0, 4.57]}>
              <T.Mesh
                name="Object_20"
                geometry={gltf.nodes.Object_20.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear009_9" position={[-1, 0, 4.51]}>
              <T.Mesh
                name="Object_22"
                geometry={gltf.nodes.Object_22.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear010_10" position={[0.93, 0, 2.92]}>
              <T.Mesh
                name="Object_24"
                geometry={gltf.nodes.Object_24.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear011_11" position={[-2.08, 0, 2.59]}>
              <T.Mesh
                name="Object_26"
                geometry={gltf.nodes.Object_26.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear012_12" position={[3.84, 0, 8.51]}>
              <T.Mesh
                name="Object_28"
                geometry={gltf.nodes.Object_28.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear013_13" position={[4.92, 0, 7.47]}>
              <T.Mesh
                name="Object_30"
                geometry={gltf.nodes.Object_30.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear014_14" position={[5.33, 0, 5.01]}>
              <T.Mesh
                name="Object_32"
                geometry={gltf.nodes.Object_32.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear015_15" position={[2.85, 0, 6.73]}>
              <T.Mesh
                name="Object_34"
                geometry={gltf.nodes.Object_34.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear016_16" position={[4.74, 0, -4.61]}>
              <T.Mesh
                name="Object_36"
                geometry={gltf.nodes.Object_36.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear017_17" position={[3.37, 0, -5.21]}>
              <T.Mesh
                name="Object_38"
                geometry={gltf.nodes.Object_38.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear018_120" position={[8.09, 0, -2.01]}>
              <T.Mesh
                name="Object_40"
                geometry={gltf.nodes.Object_40.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear019_121" position={[7.12, 0, -0.87]}>
              <T.Mesh
                name="Object_42"
                geometry={gltf.nodes.Object_42.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear020_122" position={[7.61, 0, 2.98]}>
              <T.Mesh
                name="Object_44"
                geometry={gltf.nodes.Object_44.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear021_123" position={[9.09, 0, 3.22]}>
              <T.Mesh
                name="Object_46"
                geometry={gltf.nodes.Object_46.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear023_124" position={[7.01, 0, 1.6]}>
              <T.Mesh
                name="Object_48"
                geometry={gltf.nodes.Object_48.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear022_125" position={[-2.52, 0, -0.26]}>
              <T.Mesh
                name="Object_50"
                geometry={gltf.nodes.Object_50.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear024_126" position={[-1.35, 0, 0.68]}>
              <T.Mesh
                name="Object_52"
                geometry={gltf.nodes.Object_52.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear025_127" position={[-0.68, 0, 6.01]}>
              <T.Mesh
                name="Object_54"
                geometry={gltf.nodes.Object_54.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear026_128" position={[-2.18, 0, 6.05]}>
              <T.Mesh
                name="Object_56"
                geometry={gltf.nodes.Object_56.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear027_129" position={[-1.43, 0, -2.74]}>
              <T.Mesh
                name="Object_58"
                geometry={gltf.nodes.Object_58.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear028_130" position={[-3.69, 0, 1.37]}>
              <T.Mesh
                name="Object_60"
                geometry={gltf.nodes.Object_60.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear029_131" position={[7.96, 0, 6.48]}>
              <T.Mesh
                name="Object_62"
                geometry={gltf.nodes.Object_62.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear030_132" position={[8.32, 0, 0.75]}>
              <T.Mesh
                name="Object_64"
                geometry={gltf.nodes.Object_64.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear031_133" position={[0.4, 0, 7.73]}>
              <T.Mesh
                name="Object_66"
                geometry={gltf.nodes.Object_66.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear033_134" position={[2.18, 0, 5.38]}>
              <T.Mesh
                name="Object_68"
                geometry={gltf.nodes.Object_68.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear032_135" position={[1.18, 0, 5.43]}>
              <T.Mesh
                name="Object_70"
                geometry={gltf.nodes.Object_70.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear034_136" position={[-2.82, 0, -2.09]}>
              <T.Mesh
                name="Object_72"
                geometry={gltf.nodes.Object_72.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear035_137" position={[6.27, 0, -4.6]}>
              <T.Mesh
                name="Object_74"
                geometry={gltf.nodes.Object_74.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear036_138" position={[7.19, 0, -3.52]}>
              <T.Mesh
                name="Object_76"
                geometry={gltf.nodes.Object_76.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear037_139" position={[9.55, 0, -0.15]}>
              <T.Mesh
                name="Object_78"
                geometry={gltf.nodes.Object_78.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear038_140" position={[9.37, 0, -1.16]}>
              <T.Mesh
                name="Object_80"
                geometry={gltf.nodes.Object_80.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear039_141" position={[10.14, 0, 3.21]}>
              <T.Mesh
                name="Object_82"
                geometry={gltf.nodes.Object_82.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear040_142" position={[9.75, 0, 1.28]}>
              <T.Mesh
                name="Object_84"
                geometry={gltf.nodes.Object_84.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear041_143" position={[9.26, 0, 5.62]}>
              <T.Mesh
                name="Object_86"
                geometry={gltf.nodes.Object_86.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear042_144" position={[7.18, 0, 7.78]}>
              <T.Mesh
                name="Object_88"
                geometry={gltf.nodes.Object_88.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear043_145" position={[8.63, 0, 4.78]}>
              <T.Mesh
                name="Object_90"
                geometry={gltf.nodes.Object_90.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear044_146" position={[9.57, 0, 4.37]}>
              <T.Mesh
                name="Object_92"
                geometry={gltf.nodes.Object_92.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear045_147" position={[5.79, 0, 8.04]}>
              <T.Mesh
                name="Object_94"
                geometry={gltf.nodes.Object_94.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear046_148" position={[1.94, 0, 8.04]}>
              <T.Mesh
                name="Object_96"
                geometry={gltf.nodes.Object_96.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear047_149" position={[-3.64, 0, 3.54]}>
              <T.Mesh
                name="Object_98"
                geometry={gltf.nodes.Object_98.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear082_150" position={[-0.56, 0, -4.44]}>
              <T.Mesh
                name="Object_100"
                geometry={gltf.nodes.Object_100.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear048_151" position={[-1.36, 0, -4.01]}>
              <T.Mesh
                name="Object_102"
                geometry={gltf.nodes.Object_102.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear049_152" position={[-0.81, 0, -1.58]}>
              <T.Mesh
                name="Object_104"
                geometry={gltf.nodes.Object_104.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear050_153" position={[-3.18, 0, -1.38]}>
              <T.Mesh
                name="Object_106"
                geometry={gltf.nodes.Object_106.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear051_154" position={[-1.34, 0, -0.74]}>
              <T.Mesh
                name="Object_108"
                geometry={gltf.nodes.Object_108.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear052_155" position={[-3.74, 0, -0.68]}>
              <T.Mesh
                name="Object_110"
                geometry={gltf.nodes.Object_110.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear053_156" position={[-3.93, 0, 0.12]}>
              <T.Mesh
                name="Object_112"
                geometry={gltf.nodes.Object_112.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear054_157" position={[-4.08, 0, 2.9]}>
              <T.Mesh
                name="Object_114"
                geometry={gltf.nodes.Object_114.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear055_158" position={[-2.3, 0, 6.85]}>
              <T.Mesh
                name="Object_116"
                geometry={gltf.nodes.Object_116.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear056_159" position={[-0.89, 0, 7.78]}>
              <T.Mesh
                name="Object_118"
                geometry={gltf.nodes.Object_118.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear057_160" position={[-0.99, 0, 7.23]}>
              <T.Mesh
                name="Object_120"
                geometry={gltf.nodes.Object_120.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear058_161" position={[-1.82, 0, 7.06]}>
              <T.Mesh
                name="Object_122"
                geometry={gltf.nodes.Object_122.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear059_162" position={[1.55, 0, 6.71]}>
              <T.Mesh
                name="Object_124"
                geometry={gltf.nodes.Object_124.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear060_163" position={[0.99, 0, 8.88]}>
              <T.Mesh
                name="Object_126"
                geometry={gltf.nodes.Object_126.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear061_164" position={[1.51, 0, 8.72]}>
              <T.Mesh
                name="Object_128"
                geometry={gltf.nodes.Object_128.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear062_165" position={[2.77, 0, 9.26]}>
              <T.Mesh
                name="Object_130"
                geometry={gltf.nodes.Object_130.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear063_166" position={[2.27, 0, 9.05]}>
              <T.Mesh
                name="Object_132"
                geometry={gltf.nodes.Object_132.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear064_167" position={[5.16, 0, 8.59]}>
              <T.Mesh
                name="Object_134"
                geometry={gltf.nodes.Object_134.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear065_168" position={[6.55, 0, 8.22]}>
              <T.Mesh
                name="Object_136"
                geometry={gltf.nodes.Object_136.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear066_169" position={[6.33, 0, 7.05]}>
              <T.Mesh
                name="Object_138"
                geometry={gltf.nodes.Object_138.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear067_170" position={[7.64, 0, 4.99]}>
              <T.Mesh
                name="Object_140"
                geometry={gltf.nodes.Object_140.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear068_171" position={[8.02, 0, 4.24]}>
              <T.Mesh
                name="Object_142"
                geometry={gltf.nodes.Object_142.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear069_172" position={[8.58, 0, 2.06]}>
              <T.Mesh
                name="Object_144"
                geometry={gltf.nodes.Object_144.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear070_173" position={[10.61, 0, 2.57]}>
              <T.Mesh
                name="Object_146"
                geometry={gltf.nodes.Object_146.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear071_174" position={[9.33, 0, 2.48]}>
              <T.Mesh
                name="Object_148"
                geometry={gltf.nodes.Object_148.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear072_175" position={[10.43, 0, 1.68]}>
              <T.Mesh
                name="Object_150"
                geometry={gltf.nodes.Object_150.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear073_176" position={[10.01, 0, 0.51]}>
              <T.Mesh
                name="Object_152"
                geometry={gltf.nodes.Object_152.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear074_177" position={[10.28, 0, -0.48]}>
              <T.Mesh
                name="Object_154"
                geometry={gltf.nodes.Object_154.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear075_178" position={[8.02, 0, -3.37]}>
              <T.Mesh
                name="Object_156"
                geometry={gltf.nodes.Object_156.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear076_179" position={[9.3, 0, -2.43]}>
              <T.Mesh
                name="Object_158"
                geometry={gltf.nodes.Object_158.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear077_180" position={[6.95, 0, -4.25]}>
              <T.Mesh
                name="Object_160"
                geometry={gltf.nodes.Object_160.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear078_181" position={[3.84, 0, -3.61]}>
              <T.Mesh
                name="Object_162"
                geometry={gltf.nodes.Object_162.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear079_182" position={[5.09, 0, -3.35]}>
              <T.Mesh
                name="Object_164"
                geometry={gltf.nodes.Object_164.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear080_183" position={[2.42, 0, -5.56]}>
              <T.Mesh
                name="Object_166"
                geometry={gltf.nodes.Object_166.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear081_184" position={[7.1, 0, 0.35]}>
              <T.Mesh
                name="Object_168"
                geometry={gltf.nodes.Object_168.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear083_185" position={[6.35, 0, 2.58]}>
              <T.Mesh
                name="Object_170"
                geometry={gltf.nodes.Object_170.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear084_186" position={[3.52, 0, 3.06]}>
              <T.Mesh
                name="Object_172"
                geometry={gltf.nodes.Object_172.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear085_187" position={[2.51, 0, 4.61]}>
              <T.Mesh
                name="Object_174"
                geometry={gltf.nodes.Object_174.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
            <T.Group name="Gear086_188" position={[0.83, 0, 6.5]}>
              <T.Mesh
                name="Object_176"
                geometry={gltf.nodes.Object_176.geometry}
                material={gltf.materials['Material.001']}
              />
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
