<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!-- @migration-task Error while migrating Svelte code: This migration would change the name of a slot making the component unusable -->
<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 static/3d/new.glb
-->

<script>
  import {spring } from 'svelte/motion'
  import { Group, SpotLight } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { TextureLoader, RepeatWrapping, MirroredRepeatWrapping } from 'three'
  import { useLoader } from '@threlte/core'
  const texture = useLoader(TextureLoader).load('https://res.cloudinary.com/love1/image/upload/v1640020897/cropped-PicsArt_01-28-07.49.25-1_wvt4qz.png')
  texture.wrapS = MirroredRepeatWrapping;
texture.wrapT = 2048;
texture.center = 0.5,0,5
 // import { onMount } from 'svelte';
  export let s = 0
 /* onMount(()=>{
    top.set(4)
    setTimeout(top.set(0),3000)
  })*/
  export const ref = new Group()

  const gltf = useGltf('3d/new.glb')

  const component = forwardEventHandlers()
   const top = spring(0)
   export let fi = false, hover = false, scrolli = false
  $: if(fi == true){
    top.set(7,{duration:3000})
  }else if(hover == true){
      console.log("true")
    top.set(1.5,{duration:3000})
  }else if(scrolli == true){
    top.set(0.5,{duration:3000})
  }else{
    top.set(0,{duration:3000})
  }
   let rotationt = 0
  export let poz = {z:0, y:0, x:0};

    let arr = new Array(100)
</script>
<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
  <T.AmbientLight  />
  <T.AmbientLight    intensity={1} rotation={345}/>

<T.AmbientLight  intensity={1} />


<T.SpotLight position={{ y: -20, z: -5, x: 5 }} />

<T.DirectionalLight   intensity={0.81} position={{ y: -20, z: -5, x: 5 }} />
<T.DirectionalLight  intensity={0.91} position={{ y: 10, z: 10 }} />
<T.DirectionalLight  intensity={0.91} position={[ 0,-2,0 ]} />
    <T.Group position={[(-poz.y/10)-2.4, $top+(-1.5), 0.45]} scale={0.008}>

    <T.Mesh
      geometry={gltf.nodes.mesh_0.geometry}
      material={gltf.nodes.mesh_0.material}
      position={[0.01, 0.35, -0.27]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
        </T.Group>

    <T.Mesh
      geometry={gltf.nodes.mesh_1.geometry}
      material={gltf.nodes.mesh_1.material}
      position={[0.01, 0.35, -0.27]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh_2.geometry}
      material={gltf.nodes.mesh_2.material}
      position={[0.01, 0.35, -0.27]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Group rotation={[(poz.y/20)-2.1,(poz.y/20),0]}
      position={[-0.01,fi == true? $top*2+(-3) : $top+(-3), 0.01]}
      scale={1.29}>
      <T.Mesh geometry={gltf.nodes.mesh_3.geometry} material={gltf.materials.Metallic} />
      <T.Mesh geometry={gltf.nodes.mesh_3_1.geometry} material={gltf.materials.Metallic} />
      <T.Mesh geometry={gltf.nodes.mesh_3_2.geometry} material={gltf.materials.Metallic} />
    </T.Group>
        <T.SpotLight position={[-0.01,fi == true? $top*2+(-3) : $top+(-3), 0.01]} />
      <T.SpotLight position={[-0.01, 2.4-$top/8, 0.31]}/>
          <T.SpotLight position={[-0.01, $top+2.4, 0.31]} />
      <T.SpotLight position={[-0.01, 2.4-$top/8, 0.31]}/>
    <T.Mesh
      geometry={gltf.nodes.mesh_4.geometry}
      material={gltf.nodes.mesh_4.material}
      position={[0.01, 0.35, -0.27]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh_5.geometry}
      material={gltf.nodes.mesh_5.material}
      position={[0.01, 0.35, -0.27]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh_6.geometry}
      material={gltf.nodes.mesh_6.material}
      position={[0.01, 0.35, -0.27]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
