<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/3d/withlev.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/static\3d\withlev.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[-0.08, -0.02, 0]}
      scale={0}
    >
      <T.Group
        position={[-109.08, 121.72, 531.3]}
        rotation={[-0.47, 0, 0]}
      >
        <T.Mesh
          geometry={gltf.nodes.mesh_id99.geometry}
          material={gltf.materials['90']}
          position={[-162, -20.95, 7.5]}
        />
      </T.Group>
      <T.Mesh
        geometry={gltf.nodes.node_id118.geometry}
        material={gltf.materials['85']}
        position={[-293.03, 98.87, 545.82]}
        rotation={[-0.35, 0, 0]}
        scale={14.02}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.node_id74.geometry}
      material={gltf.materials['70']}
      position={[-0.2, -0.19, 0.21]}
      rotation={[0.34, 0.49, -0.16]}
      scale={0.03}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
